stages:
    - deploy

deploy_to_test:
    stage: deploy
    environment:
        name: dev
        url: http://$DROPLET_IP
    only:
        - dep/test
    before_script:
        - apk update && apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$DEPLOY_SSH_KEY" | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh -t root@${DROPLET_IP} 'echo $HOME'
    script:
        - apk add rsync

        # Push code to the droplet using rsync
        - ssh root@$DROPLET_IP 'mkdir -p /var/www/container'

        - rsync -avz --exclude='.git' --exclude='.gitlab-ci.yml' . root@$DROPLET_IP:/var/www/container
        - scp .env.${CI_ENVIRONMENT_NAME} root@$DROPLET_IP:/var/www/container/.env
        
        # Run Docker commands on the droplet
        - ssh root@$DROPLET_IP "
            cd /var/www/container && \
            docker compose build && \
            docker compose up -d
            "
